go: bump to 1.16

diff --git a/extra/go/patches/no-bash.patch b/extra/go/patches/no-bash.patch
--- a/extra/go/patches/no-bash.patch
+++ b/extra/go/patches/no-bash.patch
@@ -1,6 +1,6 @@
 diff -ur a/go-current/src/make.bash b/go-current/src/make.bash
---- a/go-current/src/make.bash	2020-12-03 20:32:44.000000000 +0300
-+++ b/go-current/src/make.bash	2021-01-02 00:36:42.692155781 +0300
+--- a/go-current/src/make.bash	2021-02-16 21:12:04.000000000 +0300
++++ b/go-current/src/make.bash	2021-02-17 00:42:09.963840381 +0300
 @@ -1,4 +1,4 @@
 -#!/usr/bin/env bash
 +#!/bin/sh
@@ -30,12 +30,12 @@ diff -ur a/go-current/src/make.bash b/go-current/src/make.bash
  	fi
 -done; unset IFS
 +done
- GOROOT_BOOTSTRAP_VERSION=$($GOROOT_BOOTSTRAP/bin/go version | sed 's/go version //')
- echo "Building Go cmd/dist using $GOROOT_BOOTSTRAP. ($GOROOT_BOOTSTRAP_VERSION)"
- if $verbose; then
+ if [ ! -x "$GOROOT_BOOTSTRAP/bin/go" ]; then
+ 	echo "ERROR: Cannot find $GOROOT_BOOTSTRAP/bin/go." >&2
+ 	echo "Set \$GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4." >&2
 diff -ur a/go1.4-bootstrap/src/make.bash b/go1.4-bootstrap/src/make.bash
 --- a/go1.4-bootstrap/src/make.bash	2017-11-22 04:33:58.000000000 +0300
-+++ b/go1.4-bootstrap/src/make.bash	2021-01-02 00:11:00.448427915 +0300
++++ b/go1.4-bootstrap/src/make.bash	2021-02-17 00:40:52.245631282 +0300
 @@ -1,4 +1,4 @@
 -#!/usr/bin/env bash
 +#!/bin/sh
